version: '3.9'
services :
  eve_sde_db:
    image: postgres:17-alpine
    container_name: eve_sde_db
    ports:
      - "5433:5432" # Non-standard 5433 port to not clash with your own db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sde
networks:
  default:
    name: ${DOCKER_NETWORK_NAME:-eve-dev-net}
