version: '3.9'
services :
  eve_sde_db:
    image: postgres:13-alpine
    container_name: eve_sde_db
    env_file:
      - config/.env
    volumes:
      - ./database_storage:/var/lib/postgresql/data

networks:
  default:
    name: eve-sde-db
