name: Build SDE images
on:
  workflow_dispatch:
    inputs:
      date-tag:
        description: "Dump timestamp. e.g. 2021-10-13_17-31"
        required: true
      checksum-tag:
        description: "Dump md5 checksum"
        required: true

jobs:
  build-images:
    name: Build images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - env: .env.gha.schema
            tag-suffix: "-schema"
          - env: .env.gha.public
            tag-suffix: ""

    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel

      - name: Check out code
        uses: actions/checkout@v4

      - name: Start env
        run: docker compose up -d

      - name: Install dependencies
        run: pipenv install

      - name: Restore dump
        run: ./sde_updater.sh -e ${{ matrix.env }}

      - name: Move db from host to image
        run: |
          docker compose exec -T eve_sde_db mkdir /data
          docker compose exec -T eve_sde_db sh -c "cp -r /var/lib/postgresql/data/* /data"

      - name: Commit to image
        run: docker commit eve_sde_db eve_sde_build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            mjuopperi/eve_sde:latest${{ matrix.tag-suffix }}
            mjuopperi/eve_sde:${{ github.event.inputs.date-tag }}${{ matrix.tag-suffix }}
            mjuopperi/eve_sde:${{ github.event.inputs.checksum-tag }}${{ matrix.tag-suffix }}
